services:
  beapp.service.param_builder:
    class: Beapp\RepositoryTesterBundle\Service\ParamBuilder
    arguments:
      - '@monolog.logger'

  beapp.service.class_parser:
    class: Beapp\RepositoryTesterBundle\Service\ClassParser
    arguments:
      - '@monolog.logger'

  beapp.service.repository:
    class: Beapp\RepositoryTesterBundle\Service\Repository\RepositoryService
    arguments:
      - '@doctrine.orm.entity_manager.abstract'
      - '@monolog.logger'

  beapp.service.repository_tester:
    class: Beapp\RepositoryTesterBundle\Service\Repository\RepositoryTester
    arguments:
      - '@monolog.logger'
      - '@beapp.service.repository'
      - '@beapp.service.param_builder'
      - '@beapp.service.class_parser'

  beapp.command.test_repository:
    class: Beapp\RepositoryTesterBundle\Command\TestRepositoryCommand
    arguments:
      - '@beapp.service.repository_tester'
    tags:
      - { name: console.command }
